[package]
name = "uff" # Untitled Fuzzel Frontend
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
bitcode = "0.6.6"
colog = "1.3.0"
kdl = "6.3.4"
log = "0.4.27"
sha2 = "0.10.9"
walkdir = "2.5.0"
